set nocompatible " 关闭兼容模式

let vimrcs = {
			\ "plugs":			"Vundle插件管理及插件内容",
			\ "statusline":		"状态栏与标签页设置",
			\ "codecmd":		"代码设置",
			\ "keybind":		"自己设的快捷键",
			\ "match":			"符号自动匹配",
			\ "myset":			"自行设置",
			\ }

for vimrc in keys(vimrcs)
	execute "source /etc/vim/vimrcs/".vimrc.".vim"
endfor
